version: "3.8"

services:
  db:
    container_name: postgres-2
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=angelova
      - POSTGRES_PASSWORD=angelova
      - POSTGRES_DB=tamriel_db

volumes:
  postgres_data:
