version: "3.8"

services:
  db:
    container_name: postgres-airflow
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

volumes:
  postgres_data:
